spring:
  application:
    name: teste-inter

  datasource:
    url: jdbc:postgresql://localhost:5433/teste_inter
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:teste_inter;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
